### ISSUE TITLE
完整歌曲效果

### ISSUE THREAD

**Issue by dtx525942103** [dtx525942103/vits-singing-voice-synthesis#6]
https://user-images.githubusercontent.com/16432329/174228679-728bdcd1-e7e5-4524-8e24-1cabb41399a3.mp4

F0根据规则生成，没有生成颤音曲线，机器人感觉严重

**Comment by dutchsing009** [comment]
Hello , good thing you opened the repository again i emailed you about it 2 days ago. The audio above sounds so robotic and not natural at all. can you tell me exactly what is the problem here so i see if i can solve it ?? 
regarding the other issue #3 when you said "but need more detail of f0" i think i have a solution for you which is... 
you need to extract the Fundamental frequency from the audio during preprocessing , you extract that from the waveform using this https://github.com/NVIDIA/mellotron/blob/master/yin.py  
compute_yin() computes Fundamental frequency from the waveform
w_step should be the size as STFT hop size
![unknown (1)](https://user-images.githubusercontent.com/103085811/173672386-404435ba-da7d-4eba-a663-31a9795b3c7f.png)
those parameters may need to be changed for SVS since f0 can be higher than in TTS
that was my recommendation for you regarding the #3, please tell me if that works ? or if there are any other problems you also have especially regarding the so robotic audio above :)
Best Regards

**Comment by dtx525942103** [comment]
I mean need dnn network to predict smooth f0 with vibrato; The audio above sounds so robotic ,because this f0 is producted by handed(midi map) withnot vibrato; or use https://github.com/stakira/OpenUtau draw smooth f0 with vibrato;
![vibrato](https://user-images.githubusercontent.com/16432329/173724974-2fb113eb-d33a-4975-b086-6351e78063f9.gif)

**Comment by dutchsing009** [comment]
ah ok so now you are back to issue #1 again that you need vibrato for it not to have robotic sound.

**Comment by dtx525942103** [comment]
@dutchsing009 i use nn mode to predict the F0, the song is here https://github.com/dtx525942103/vits-singing-voice-synthesis/issues/8
